name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Pre Test
      run: go generate ./...

    - name: Test
      run: go test -cover -race -v ./...

    - name: Test v2
      run: go test -cover -race -v ./v2/...

    - name: Integration Test
      run: go test -tags integration ./test

    - name: Integration Test v2
      run: go test -tags integration ./v2/test
